config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  get 'relationships/followings'
  get 'relationships/followers'
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}

  devise_for :users, skip: [:passwords], controllers: {
  registrations: "user/registrations",
  passwords: 'users/passwords',
  sessions: 'user/sessions'
}
  devise_scope :user do
    post "/users/guest_sign_in" => "user/sessions#new_guest"
  end

  scope module: :user do
    root "homes#top"
    resources :chats, only: [:show, :create]
    resources :posts do
      resources :post_comments, only: [:create, :destroy, :edit, :update]
      resource :bookmarks, only: [:create, :destroy]
    end
    get "/users/unsubscribe" => "users#unsubscribe"
    patch "/users/:id/withdrawal" => "users#withdrawal", as: "withdrawal"
    resources :users, only: [:show, :edit, :update, :destroy, :index] do
      resource :favorites, only: [:create, :destroy]
      resource :relationships, only: [:create, :destroy]
  	get 'followings' => 'relationships#followings', as: 'followings'
  	get 'followers' => 'relationships#followers', as: 'followers'
    end
  end

   namespace :admin do
     get "/" => "homes#top"
     resources :users, only: [:index, :show, :update]
     resources :posts, only: [:index, :destroy, :show]
     resources :post_comments, only: [:index, :destroy]
  end

  get "/search" => "searches#search"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.page(params[:page]).per(15).reverse_order
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page]).per(10).reverse_order
    @post_comments = @user.post_comments
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    flash[:notice] = '更新が完了しました'
    redirect_to admin_user_path(@user)
  end

  private

  def user_params
    params.require(:user).permit(:name, :icon_image, :address, :age, :my_favorite, :live_stance, :status)
  end

end

app/controllers/user/bookmarks_controller.rb
class User::BookmarksController < ApplicationController
  before_action :authenticate_user!
  
  def create
    @post = Post.find(params[:post_id])
    bookmark = current_user.bookmarks.new(post_id: @post.id)
    bookmark.save
  end

  def destroy
    @post = Post.find(params[:post_id])
    bookmark = current_user.bookmarks.find_by(post_id: @post.id)
    bookmark.destroy
  end
end

app/controllers/user/chats_controller.rb
class User::ChatsController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    rooms = current_user.user_rooms.pluck(:room_id)
    user_room = UserRoom.find_by(user_id: @user.id, room_id: rooms)

    if user_room.nil?
      @room = Room.new
      @room.save
      UserRoom.create(user_id: @user.id, room_id: @room.id)
      UserRoom.create(user_id: current_user.id, room_id: @room.id)
    else
      @room = user_room.room
    end

    @chats = @room.chats
    @chat = Chat.new(room_id: @room.id)
  end

  def create
    @chat = current_user.chats.new(chat_params)
    unless @chat.save
      flash[:alert] = 'メッセージを入力してください'
    end
  end

  private

  def chat_params
    params.require(:chat).permit(:message, :room_id).merge(user_id: current_user.id)
  end

end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def top
  end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  before_action :check_guest, only: :create

  def check_guest
    if params[:user][:email].downcase == 'guest@example.com'
      flash.now[:alert] = 'ゲストユーザーの変更・削除はできません'
      redirect_to posts_path
    end
  end
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/post_comments_controller.rb
class User::PostCommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    @post_comment = current_user.post_comments.new(post_comment_params)
    @post_comment.post_id = @post.id
    unless @post_comment.save
      flash[:alert] = 'コメントを入力してください'
    end
  end

  def edit
    @post = Post.find(params[:post_id])
    @post_comment = @post.post_comments.find(params[:id])
    if @post_comment.user == current_user
      render :edit
    else
      redirect_to posts_path
    end
  end

  def update
    @post = Post.find(params[:post_id])
    @post_comment = @post.post_comments.find(params[:id])
    if @post_comment.update(post_comment_params)
      flash[:notice] = 'コメントの更新が完了しました'
      redirect_to post_path(@post)
    else
      flash[:alert] = 'コメントの更新に失敗しました'
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @post_comment = @post.post_comments.find(params[:id])
    if @post_comment.destroy
      flash[:notice] = 'コメントを削除しました'
    end
  end

  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end

end

app/controllers/user/posts_controller.rb
class User::PostsController < ApplicationController
  before_action :authenticate_user!

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    @user = @post.user
    if params[:new]
      @post.is_draft = false
      if @post.save(context: :publicize)
        flash[:notice] = '投稿が完了しました'
        redirect_to posts_path(@post)
      else
        flash.now[:alert] = '投稿に失敗しました'
        render :new
      end
    else
      if @post.update(is_draft: true)
        flash[:notice] = '下書きを保存しました'
        redirect_to user_path(@user)
      else
        flash.now[:alert] = '下書きの保存に失敗しました'
        render :new
      end
    end
  end

# 公開された投稿のみ表示（タグ検索に対応）
  def index
    @posts = params[:tag_id].present? ? Tag.find(params[:tag_id]).posts.page(params[:page]) : Post.where(is_draft: false).page(params[:page]).per(15).reverse_order
  end

  def show
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
  end

  def edit
    @post = Post.find(params[:id])
    if @post.user == current_user
      render :edit
    else
      redirect_to posts_path
    end
  end

  def update
    @post = Post.find(params[:id])
    if params[:publicize_draft]
      @post.attributes = post_params.merge(is_draft: false)
      if @post.save(context: :publicize)
        flash[:notice] = '下書きを公開しました'
        redirect_to posts_path
      else
        @post.is_draft = true
        flash.now[:alert] = '下書きの公開に失敗しました'
        render :edit
      end
    elsif params[:update_post]
      @post.attributes = post_params
      if @post.save(content: :publicize)
        flash[:notice] = '更新が完了しました'
        redirect_to post_path(@post)
      else
        flash.now[:alert] = '更新に失敗しました'
        render :edit
      end
    else
      if @post.update(post_params)
        flash[:notice] = '下書きを更新しました'
        redirect_to post_path(@post)
      else
        flash.now[:alert] = '下書きの更新に失敗しました'
        render :edit
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = '投稿を削除しました'
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:post, :user_id, :is_draft, :created_at, tag_ids: [], post_images: [])
  end

end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  before_action :check_guest, only: %i[update destroy]

  def check_guest
    if resource.email == 'guest@example.com'
      flash.now[:alert] = 'ゲストユーザーの変更・削除はできません'
      redirect_to posts_path
    end
  end
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  protected
    def after_sign_up_path_for(resource)
      posts_path
    end

end

app/controllers/user/relationships_controller.rb
class User::RelationshipsController < ApplicationController
  before_action :authenticate_user!

  def create
    @user = User.find(params[:user_id])
    current_user.follow(@user.id)
  end

  def destroy
    @user = User.find(params[:user_id])
    current_user.unfollow(@user.id)
  end

  def followed
    user = User.find(params[:user_id])
    @users = user.followers
  end

  def follower
    user = User.find(params[:user_id])
    @users = user.followings
  end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  def new_guest
    user = User.guest
    sign_in user
    flash[:notice] = 'ゲストユーザーとしてログインしました。'
    redirect_to posts_path
  end


  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  protected
    def after_sign_in_path_for(resource)
      posts_path
    end

    def reject_user
      @user = User.find_by(name: params[:user][:name])
      if @user.valid_password?(params[:user][:password]) && (@user.status == true)
        flash[:notice] = "退会済みです。再度ご登録をしてご利用ください。"
        redirect_to new_user_registration_path
      end
    end

end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  before_action :authenticate_user!


  def index
    @users = User.all
    @user = User.find_by(params[:id])
  end

  def show
    @user = User.find(params[:id])
    @followers = @user.followers
    @followings = @user.followings
    @posts = @user.posts.page(params[:page]).per(10).reverse_order
    @bookmarks = Bookmark.where(user_id: @user.id).all
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.save
      flash[:notice] = '更新が完了しました'
      redirect_to user_path(@user.id)
    else
      flash.now[:alert] = '更新に失敗しました'
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user == current_user
       @user.destroy
       flash.now[:notice] = 'アカウントを削除しました'
       redirect_to root_path
    end
  end

  def unsubscribe
    @user = current_user
  end

  def withdrawal
    @user = User.find(params[:id])
    @user.update(status: false)
    reset_session
    flash[:notice] = "退会処理が完了しました"
    redirect_to root_path
  end


  private

  def user_params
    params.require(:user).permit(:name, :icon_image, :address, :age, :my_favorite, :live_stance, :status)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/user/bookmarks_helper.rb
module User::BookmarksHelper
end

app/helpers/user/chats_helper.rb
module User::ChatsHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/helpers/user/post_comments_helper.rb
module User::PostCommentsHelper
end

app/views/user/users/edit.html.erb
<h4 class="w-75 mx-auto mt-5">プロフィール編集</h4>
<div class="w-75 mx-auto">
  <% if @user.errors.any? %>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  <div class="row">
    <div class="col-10 ml-5">
      <%= form_with model: @user, method: :patch do |f| %>
      <div class="form-group row">
        <%= f.label :name, "ニックネーム", class: "col-4 col-form-label" %>
        <div class="form-group col-6">
          <%= f.text_field :name, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group row">
        <%= f.label :icon_image, "プロフィール画像", class: "col-4 col-form-label" %>
        <div class="form-group col-6">
          <%= f.file_field :icon_image, accept:"image/*" %>
        </div>
      </div>
      <div class="form-group row">
        <%= f.label :address, "居住地", class: "col-4 col-form-label" %>
        <div class="form-group col-6">
          <%= f.select :address, User.addresses.keys, {}, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group row">
        <%= f.label :age, "年齢", class: "col-4 col-form-label" %>
        <div class="form-group col-6">
          <%= f.number_field :age, class: 'form-control', class: "hoge", min: 18, max: 100 %> 歳
        </div>
      </div>
      <div class="form-group row">
        <%= f.label :my_favorite, "推しアーティスト", class: "col-4 col-form-label" %>
        <div class="form-group col-6">
          <%= f.text_field :my_favorite, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group row">
        <%= f.label :live_stance, "ライブの楽しみ方", class: "col-4 col-form-label" %>
        <div class="form-group col-6">
          <%= f.select :live_stance, User.live_stances.keys, {}, class: 'form-control' %>
        </div>
      </div>
      <div class="d-flex justify-content-center mb-5">
        <%= f.submit "編集完了", class: "btn btn-outline-info mr-3" %>
        <%= link_to "退会する", users_unsubscribe_path(@user), class: "btn btn-outline-danger" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/user/users/index.html.erb
<div class="w-75 mb-2 mx-auto">
  <%= render '/user/posts/new_post' %>
</div>
<h4 class="w-75 mx-auto mt-5">すべてのユーザー</h4>
<div class="mx-auto mt-3">
  <%= render '/user/users/card', users: @users, user: @user %>
</div>

app/views/user/users/show.html.erb
<div class="w-75 mx-auto">
  <%= render '/user/posts/new_post' %>
</div>
<h4 class="w-75 mx-auto mt-5">
  <% if @user == current_user %>
    マイページ
  <% else %>
    <%= @user.name %> さんのページ
  <% end %>
</h4>
<!--ユーザープロフィール-->
<div class="card text-center w-75 mx-auto my-2 shadow-sm">
  <div class="card-header d-flex justify-content-center align-items-center font-weight-bolder text-white bg-info">
    <%= image_tag @user.get_icon_image(120, 120), class: "border rounded-circle mr-3" %>
    <div>
      <div>
        <%= @user.name %>
      </div>
      <div>
        <% if @user == current_user %>
          <%= link_to edit_user_path(@user), class: "btn btn-outline-dark btn-sm" do %>
            <i class="fas fa-user-cog"></i> 編集する
          <% end %>
          <%= link_to users_unsubscribe_path, class: "btn btn-outline-danger btn-sm" do %>
            <i class="fas fa-user-slash"></i> 退会する
          <% end %>
        <% else %>
          <div id="follow_button_<%= @user.id %>">
            <%= render "user/relationships/btn", user: @user %>
          </div>
        <% end %>
      </div>
      <div class="d-inline">
        <%= "フォロー: #{@user.relationships.count}人" %>
        <%= "フォロワー: #{@user.reverse_of_relationships.count}人" %>
      </div>
    </div>
  </div>
  <div class="card-body w-100 mx-auto">
    <div class="row">
      <div class="col-6 col-md-4 d-flex justify-content-end">
        居住地：
      </div>
      <div class="col-6 col-md-8 d-flex justify-content-start">
        <%= @user.address %>
      </div>
    </div>
    <div class="row">
      <div class="col-6 col-md-4 d-flex justify-content-end">
        年齢：
      </div>
      <div class="col-6 col-md-8 d-flex justify-content-start">
        <%= @user.age %>歳
      </div>
    </div>
    <div class="row">
      <div class="col-6 col-md-4 d-flex justify-content-end">
        推しアーティスト：
      </div>
      <div class="col-6 col-md-8 d-flex justify-content-start">
        <%= @user.my_favorite %>
      </div>
    </div>
    <div class="row">
      <div class="col-6 col-md-4 d-flex justify-content-end">
        ライブの楽しみ方：
      </div>
      <div class="col-6 col-md-8 d-flex justify-content-start">
        <%= @user.live_stance %>
      </div>
    </div>
    <div class="mt-2">
      <% if current_user != @user && current_user.following?(@user) && @user.following?(current_user) %>
        <%= link_to "チャット", chat_path(@user), class: "btn btn-info btn-sm" %>
      <% end %>
    </div>
  </div>
</div>

<!--画面下部のタブ部分-->
<nav class="w-75 mx-auto mt-5">
  <div class="nav nav-tabs" id="nav-tab" role="tablist">
    <a class="nav-item nav-link active" id="nav-post-tab" data-toggle="tab" href="#nav-post" role="tab" aria-controls="nav-post" aria-selected="true">投稿一覧</a>
    <a class="nav-item nav-link" id="nav-comment-tab" data-toggle="tab" href="#nav-comment" role="tab" aria-controls="nav-comment" aria-selected="false">コメント一覧</a>
    <a class="nav-item nav-link" id="nav-bookmark-tab" data-toggle="tab" href="#nav-bookmark" role="tab" aria-controls="nav-bookmark" aria-selected="false">いいねした投稿</a>
    <a class="nav-item nav-link" id="nav-followings-tab" data-toggle="tab" href="#nav-followings" role="tab" aria-controls="nav-followings" aria-selected="false">フォロー</a>
    <a class="nav-item nav-link" id="nav-followers-tab" data-toggle="tab" href="#nav-followers" role="tab" aria-controls="nav-followers" aria-selected="false">フォロワー</a>
  </div>
</nav>
<!--投稿・下書き一覧タブ-->
<div class="tab-content" id="nav-tabContent">
  <div class="tab-pane fade show active" id="nav-post" role="tabpanel" aria-labelledby="nav-post-tab">
    <% unless @posts.present? %>
      <p class="w-75 mx-auto">まだ投稿がありません</p>
    <% end %>
    <% @posts.each do |post| %>
      <% if post.is_draft && @user == current_user %>
        <div class="card w-75 mx-auto my-2 shadow-sm">
          <div class="card-header font-weight-bolder text-white <%= post.is_draft ? "bg-secondary" : "bg-info" %>">
            <%= image_tag post.user.get_icon_image(50,50), class: "border rounded-circle" %>
            <%= post.user.name %>
          </div>
          <a href="/posts/<%= post.id %>" class="card-body text-dark ">
            <div class="card-body">
              <p><%= post.post %></p>
              <% post.tags.each do |tag| %>
                <%= tag.name %>
              <% end %><br>
              <% post.post_images.each do |post_image| %>
                <%= image_tag post_image, size: "80x80" %>
              <% end %>
            </div>
          </a>
          <div class="blockquote-footer text-right px-2 pb-3">
            <%= l post.created_at, format: :short %>
            <div id="bookmark_buttons_<%= post.id %>" class="d-inline">
              <%= render "/user/bookmarks/bookmark", post: post %>
            </div>
            <div id="comment_counts" class="d-inline mx-1">
              <%= render "/user/post_comments/comment_icon", post: post %>
            </div>
            <% if post.user == current_user %>
              <%= link_to edit_post_path(post), class: "btn btn-secondary btn-sm rounded-circle" do %>
                <i class="fas fa-edit"></i>
              <% end %>
            <% end %>
            <% if post.user == current_user %>
              <%= link_to post_path(post), method: :delete, data: {confirm: "削除しますか？"}, class: "btn btn-secondary btn-sm rounded-circle" do %>
                <i class="fas fa-trash-alt"></i>
              <% end %>
            <% end %>
          </div>
        </div>
      <% elsif !post.is_draft %>
        <div class="card w-75 mx-auto my-2 shadow-sm">
          <div class="card-header font-weight-bolder text-white <%= post.is_draft ? "bg-secondary" : "bg-info" %>">
            <%= image_tag post.user.get_icon_image(50,50), class: "border rounded-circle" %>
            <%= post.user.name %>
          </div>
          <a href="/posts/<%= post.id %>" class="card-body text-dark ">
          <div class="card-body">
              <p><%= post.post %></p>
              <% post.tags.each do |tag| %>
                <%= tag.name %>
              <% end %><br>
              <% post.post_images.each do |post_image| %>
                <%= image_tag post_image, size: "80x80" %>
              <% end %>
          </div>
          </a>
          <div class="blockquote-footer text-right px-2 pb-3">
            <%= l post.created_at, format: :short %>
            <div id="bookmark_buttons_<%= post.id %>" class="d-inline">
              <%= render "/user/bookmarks/bookmark", post: post %>
            </div>
            <div id="comment_counts" class="d-inline mx-1">
              <%= render "/user/post_comments/comment_icon", post: post %>
            </div>
            <% if post.user == current_user %>
              <%= link_to edit_post_path(post), class: "btn btn-secondary btn-sm rounded-circle" do %>
                <i class="fas fa-edit"></i>
              <% end %>
            <% end %>
            <% if post.user == current_user %>
              <%= link_to post_path(post), method: :delete, data: {confirm: "削除しますか？"}, class: "btn btn-secondary btn-sm rounded-circle" do %>
                <i class="fas fa-trash-alt"></i>
              <% end %>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
    <div class="row justify-content-center">
      <%= paginate @posts %>
    </div>
  </div>
  <!--コメント一覧タブ-->
  <div class="tab-pane fade" id="nav-comment" role="tabpanel" aria-labelledby="nav-comment-tab">
    <% unless @user.post_comments.present? %>
      <p class="w-75 mx-auto">まだコメントがありません</p>
    <% end %>
    <%= render '/user/post_comments/comment', post_comments: @user.post_comments, post: @post %>
  </div>
  <!--いいねした投稿一覧タブ-->
  <div class="tab-pane fade" id="nav-bookmark" role="tabpanel" aria-labelledby="nav-bookmark-tab">
    <% unless @bookmarks.present? %>
      <p class="w-75 mx-auto">まだいいねした投稿がありません</p>
    <% end %>
    <% if @bookmarks.present? %>
      <% @bookmarks.each do |bookmark| %>
        <% post = bookmark.post %>
        <div class="card w-75 mx-auto my-2 shadow-sm">
          <div class="card-header font-weight-bolder text-white bg-info">
            <%= image_tag post.user.get_icon_image(50,50), class: "border rounded-circle" %>
            <%= post.user.name %>
          </div>
          <a href="/posts/<%= post.id %>" class="card-body text-dark ">
          <div class="card-body">
            <p><%= post.post %></p>
            <% post.tags.each do |tag| %>
              <%= tag.name %>
            <% end %><br>
            <% post.post_images.each do |post_image| %>
              <%= image_tag post_image, size: "80x80" %>
            <% end %>
          </div>
          </a>
          <div class="blockquote-footer text-right px-2 pb-3">
            <%= l post.created_at, format: :short %>
            <div id="bookmark_buttons_<%= post.id %>" class="d-inline">
              <%= render "/user/bookmarks/bookmark", post: post %>
            </div>
            <div class="mx-1 d-inline"><i class="fas fa-comments"></i><%= post.post_comments.count %></div>
            <% if post.user == current_user %>
              <%= link_to edit_post_path(post), class: "btn btn-secondary btn-sm rounded-circle" do %>
                <i class="fas fa-edit"></i>
              <% end %>
            <% end %>
            <% if post.user == current_user %>
              <%= link_to post_path(post), method: :delete, class: "btn btn-secondary btn-sm rounded-circle" do %>
                <i class="fas fa-trash-alt"></i>
              <% end %>
            <% end %>
          </div>
        </div>
      <% end %>
      <% end %>
  </div>
    <!--フォロータブ-->
  <div class="tab-pane fade" id="nav-followings" role="tabpanel" aria-labelledby="nav-followings-tab">
    <%= render '/user/relationships/followed', followings: @followings %>
  </div>
    <!--フォロワータブ-->
  <div class="tab-pane fade" id="nav-followers" role="tabpanel" aria-labelledby="nav-followers-tab">
    <%= render '/user/relationships/follower', followers: @followers %>
  </div>
</div>