config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  get 'relationships/followings'
  get 'relationships/followers'
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}

  devise_for :users, skip: [:passwords], controllers: {
  registrations: "user/registrations",
  passwords: 'users/passwords',
  sessions: 'user/sessions'
}
  devise_scope :user do
    post "/users/guest_sign_in" => "user/sessions#new_guest"
  end

  scope module: :user do
    root "homes#top"
    resources :chats, only: [:show, :create]
    resources :posts do
      resources :post_comments, only: [:create, :destroy, :edit, :update]
      resource :bookmarks, only: [:create, :destroy]
    end
    get "/users/unsubscribe" => "users#unsubscribe"
    patch "/users/:id/withdrawal" => "users#withdrawal", as: "withdrawal"
    resources :users, only: [:show, :edit, :update, :destroy, :index] do
      resource :favorites, only: [:create, :destroy]
      resource :relationships, only: [:create, :destroy]
  	get 'followings' => 'relationships#followings', as: 'followings'
  	get 'followers' => 'relationships#followers', as: 'followers'
    end
  end

   namespace :admin do
     get "/" => "homes#top"
     resources :users, only: [:index, :show, :update]
     resources :posts, only: [:index, :destroy, :show]
     resources :post_comments, only: [:index, :destroy]
  end

  get "/search" => "searches#search"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.page(params[:page]).per(15).reverse_order
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page]).per(10).reverse_order
    @post_comments = @user.post_comments
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    flash[:notice] = '更新が完了しました'
    redirect_to admin_user_path(@user)
  end

  private

  def user_params
    params.require(:user).permit(:name, :icon_image, :address, :age, :my_favorite, :live_stance, :status)
  end

end

app/controllers/user/bookmarks_controller.rb
class User::BookmarksController < ApplicationController
  before_action :authenticate_user!
  
  def create
    @post = Post.find(params[:post_id])
    bookmark = current_user.bookmarks.new(post_id: @post.id)
    bookmark.save
  end

  def destroy
    @post = Post.find(params[:post_id])
    bookmark = current_user.bookmarks.find_by(post_id: @post.id)
    bookmark.destroy
  end
end

app/controllers/user/chats_controller.rb
class User::ChatsController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    rooms = current_user.user_rooms.pluck(:room_id)
    user_room = UserRoom.find_by(user_id: @user.id, room_id: rooms)

    if user_room.nil?
      @room = Room.new
      @room.save
      UserRoom.create(user_id: @user.id, room_id: @room.id)
      UserRoom.create(user_id: current_user.id, room_id: @room.id)
    else
      @room = user_room.room
    end

    @chats = @room.chats
    @chat = Chat.new(room_id: @room.id)
  end

  def create
    @chat = current_user.chats.new(chat_params)
    unless @chat.save
      flash[:alert] = 'メッセージを入力してください'
    end
  end

  private

  def chat_params
    params.require(:chat).permit(:message, :room_id).merge(user_id: current_user.id)
  end

end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def top
  end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  before_action :check_guest, only: :create

  def check_guest
    if params[:user][:email].downcase == 'guest@example.com'
      flash.now[:alert] = 'ゲストユーザーの変更・削除はできません'
      redirect_to posts_path
    end
  end
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/post_comments_controller.rb
class User::PostCommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    @post_comment = current_user.post_comments.new(post_comment_params)
    @post_comment.post_id = @post.id
    unless @post_comment.save
      flash[:alert] = 'コメントを入力してください'
    end
  end

  def edit
    @post = Post.find(params[:post_id])
    @post_comment = @post.post_comments.find(params[:id])
    if @post_comment.user == current_user
      render :edit
    else
      redirect_to posts_path
    end
  end

  def update
    @post = Post.find(params[:post_id])
    @post_comment = @post.post_comments.find(params[:id])
    if @post_comment.update(post_comment_params)
      flash[:notice] = 'コメントの更新が完了しました'
      redirect_to post_path(@post)
    else
      flash[:alert] = 'コメントの更新に失敗しました'
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @post_comment = @post.post_comments.find(params[:id])
    if @post_comment.destroy
      flash[:notice] = 'コメントを削除しました'
    end
  end

  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end

end

app/controllers/user/posts_controller.rb
class User::PostsController < ApplicationController
  before_action :authenticate_user!

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    @user = @post.user
    if params[:new]
      @post.is_draft = false
      if @post.save(context: :publicize)
        flash[:notice] = '投稿が完了しました'
        redirect_to posts_path(@post)
      else
        flash.now[:alert] = '投稿に失敗しました'
        render :new
      end
    else
      if @post.update(is_draft: true)
        flash[:notice] = '下書きを保存しました'
        redirect_to user_path(@user)
      else
        flash.now[:alert] = '下書きの保存に失敗しました'
        render :new
      end
    end
  end

# 公開された投稿のみ表示（タグ検索に対応）
  def index
    @posts = params[:tag_id].present? ? Tag.find(params[:tag_id]).posts.page(params[:page]) : Post.where(is_draft: false).page(params[:page]).per(15).reverse_order
  end

  def show
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
  end

  def edit
    @post = Post.find(params[:id])
    if @post.user == current_user
      render :edit
    else
      redirect_to posts_path
    end
  end

  def update
    @post = Post.find(params[:id])
    if params[:publicize_draft]
      @post.attributes = post_params.merge(is_draft: false)
      if @post.save(context: :publicize)
        flash[:notice] = '下書きを公開しました'
        redirect_to posts_path
      else
        @post.is_draft = true
        flash.now[:alert] = '下書きの公開に失敗しました'
        render :edit
      end
    elsif params[:update_post]
      @post.attributes = post_params
      if @post.save(content: :publicize)
        flash[:notice] = '更新が完了しました'
        redirect_to post_path(@post)
      else
        flash.now[:alert] = '更新に失敗しました'
        render :edit
      end
    else
      if @post.update(post_params)
        flash[:notice] = '下書きを更新しました'
        redirect_to post_path(@post)
      else
        flash.now[:alert] = '下書きの更新に失敗しました'
        render :edit
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = '投稿を削除しました'
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:post, :user_id, :is_draft, :created_at, tag_ids: [], post_images: [])
  end

end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  before_action :check_guest, only: %i[update destroy]

  def check_guest
    if resource.email == 'guest@example.com'
      flash.now[:alert] = 'ゲストユーザーの変更・削除はできません'
      redirect_to posts_path
    end
  end
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  protected
    def after_sign_up_path_for(resource)
      posts_path
    end

end

app/controllers/user/relationships_controller.rb
class User::RelationshipsController < ApplicationController
  before_action :authenticate_user!

  def create
    @user = User.find(params[:user_id])
    current_user.follow(@user.id)
  end

  def destroy
    @user = User.find(params[:user_id])
    current_user.unfollow(@user.id)
  end

  def followed
    user = User.find(params[:user_id])
    @users = user.followers
  end

  def follower
    user = User.find(params[:user_id])
    @users = user.followings
  end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  def new_guest
    user = User.guest
    sign_in user
    flash[:notice] = 'ゲストユーザーとしてログインしました。'
    redirect_to posts_path
  end


  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  protected
    def after_sign_in_path_for(resource)
      posts_path
    end

    def reject_user
      @user = User.find_by(name: params[:user][:name])
      if @user.valid_password?(params[:user][:password]) && (@user.status == true)
        flash[:notice] = "退会済みです。再度ご登録をしてご利用ください。"
        redirect_to new_user_registration_path
      end
    end

end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  before_action :authenticate_user!


  def index
    @users = User.all
    @user = User.find_by(params[:id])
  end

  def show
    @user = User.find(params[:id])
    @followers = @user.followers
    @followings = @user.followings
    @posts = @user.posts.page(params[:page]).per(10).reverse_order
    @bookmarks = Bookmark.where(user_id: @user.id).all
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.save
      flash[:notice] = '更新が完了しました'
      redirect_to user_path(@user.id)
    else
      flash.now[:alert] = '更新に失敗しました'
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user == current_user
       @user.destroy
       flash.now[:notice] = 'アカウントを削除しました'
       redirect_to root_path
    end
  end

  def unsubscribe
    @user = current_user
  end

  def withdrawal
    @user = User.find(params[:id])
    @user.update(status: false)
    reset_session
    flash[:notice] = "退会処理が完了しました"
    redirect_to root_path
  end


  private

  def user_params
    params.require(:user).permit(:name, :icon_image, :address, :age, :my_favorite, :live_stance, :status)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/user/bookmarks_helper.rb
module User::BookmarksHelper
end

app/helpers/user/chats_helper.rb
module User::ChatsHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/helpers/user/post_comments_helper.rb
module User::PostCommentsHelper
end

app/views/admin/users/index.html.erb
<h4 class="w-75 mx-auto mt-5">ユーザー一覧</h4>
<div class="card w-75 mx-auto my-2 shadow-sm">
  <table class="table table-hover text-center">
    <thead class="bg-info text-white">
      <tr>
        <th>会員ID</th>
        <th>ニックネーム</th>
        <th>メールアドレス</th>
        <th>年齢</th>
        <th>居住地</th>
        <th>会員ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.id %></td>
          <td>
            <%= link_to admin_user_path(user.id), class: "text-dark" do %>
              <%= user.name %>
            <% end %>
          </td>
          <td><%= user.email %></td>
          <td><%= user.age %></td>
          <td><%= user.address %></td>
          <td><% if user.status == true %>
            <p class="text-success">有効</p>
            <% else %>
            <p class="text-danger">退会</p>
            <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div class="d-flex justify-content-center">
  <%= paginate @users %>
</div>

app/views/admin/users/show.html.erb
<h4 class="w-75 mx-auto">会員詳細</h4>
<div class="card w-75 mx-auto my-3 shadow-sm">
  <div class="card-header font-weight-bolder text-white bg-info">
    <div class="row">
      <div class="col-1">
        会員ID
      </div>
      <div class="col-2">
        ニックネーム
      </div>
      <div class="col-3">
        メールアドレス
      </div>
      <div class="col-1">
        年齢
      </div>
      <div class="col-2">
        居住地
      </div>
      <div class="col-2">
        会員ステータス
      </div>
    </div>
  </div>
  <div class="card-body">
    <div class="row">
      <div class="col-1">
        <%= @user.id %>
      </div>
      <div class="col-2">
        <%= @user.name %>
      </div>
      <div class="col-3">
        <%= @user.email %>
      </div>
      <div class="col-1">
        <%= @user.age %>
      </div>
      <div class="col-2">
        <%= @user.address %>
      </div>
      <div class="col-2">
        <%= form_with model: @user, url:admin_user_path, method: :patch do |f| %>
          <%= f.select :status, [['有効',true],['退会',false]] %>
          <%= f.submit "更新", class: 'btn btn-outline-primary btn-sm' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<nav class="w-75 mx-auto">
  <div class="nav nav-tabs" id="nav-tab" role="tablist">
    <a class="nav-item nav-link active" id="nav-post-tab" data-toggle="tab" href="#nav-post" role="tab" aria-controls="nav-post" aria-selected="true">"<%= @user.name %>"の投稿一覧</a>
    <a class="nav-item nav-link" id="nav-comment-tab" data-toggle="tab" href="#nav-comment" role="tab" aria-controls="nav-comment" aria-selected="false">"<%= @user.name %>"のコメント一覧</a>
  </div>
</nav>
  <!--投稿一覧-->
<div class="tab-content" id="nav-tabContent">
  <div class="tab-pane fade show active" id="nav-post" role="tabpanel" aria-labelledby="nav-post-tab">
    <table class="table w-75 mx-auto mt-2 text-center">
      <thead class="bg-info text-white">
        <tr>
          <th>投稿ID</th>
          <th>投稿文</th>
          <th>投稿時間</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td><%= post.id %></td>

          <% if post.is_draft == true %>
            <td style="text-overflow: ellipsis; white-space: nowrap; overflow: hidden; max-width: 0;">
              <%= link_to admin_post_path(post), class: "text-dark" do %>
                #下書き<br>
                <%= post.post %>
              <% end %>
            </td>
          <% else %>
            <td style="text-overflow: ellipsis; white-space: nowrap; overflow: hidden; max-width: 0;">
              <%= link_to admin_post_path(post), class: "text-dark" do %>
                <%= post.post %>
              <% end %>
            </td>
          <% end %>
          <td><%= l post.created_at, format: :short %></td>
          <td><%= link_to "削除", admin_post_path(post), method: :delete, data: {confirm: "削除しますか？"}, class: "btn btn-danger btn-sm" %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <div class="row justify-content-center">
      <%= paginate @posts %>
    </div>
  </div>

  <!--コメント一覧-->
  <div class="tab-pane fade" id="nav-comment" role="tabpanel" aria-labelledby="nav-comment-tab">
    <table class="table w-75 mx-auto mt-2 table-hover text-center">
      <thead class="bg-info text-white">
        <tr>
          <th>元投稿のユーザー</th>
          <th>コメント</th>
          <th>投稿時間</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
      <% @post_comments.each do |post_comment| %>
      <% post = post_comment.post %>
        <tr>
          <td>＠ <%= post.user.name %></td>
          <td style="text-overflow: ellipsis; white-space: nowrap; overflow: hidden; max-width: 0;">
            <%= link_to admin_post_path(post), class: "text-truncate text-dark" do %>
              <%= post_comment.comment %>
            <% end %>
          </td>
          <td><%= l post_comment.created_at, format: :short %></td>
          <td><%= link_to "削除", admin_post_comment_path(post_comment), method: :delete, data: {confirm: "削除しますか？"}, class: "btn btn-danger btn-sm" %></td>
        </tr>
    <% end %>
      </tbody>
    </table>
  </div>
</div>